# Generated by Django 3.1.7 on 2021-04-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0003_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
