# Generated by Django 3.1.7 on 2021-08-17 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0005_resetpasswordtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 7, 47, 33, 670289)),
        ),
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='token',
            field=models.CharField(default='1629184653', max_length=100, unique=True),
        ),
    ]
