# Generated by Django 3.2.4 on 2021-12-07 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0007_auto_20210817_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecodes',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 10, 47, 10, 213033)),
        ),
        migrations.AlterField(
            model_name='generatecodes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generatecodes',
            name='token',
            field=models.CharField(default='163887', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
