# Generated by Django 3.1.7 on 2021-03-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiler', '0002_auto_20210320_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('fro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='profiler.profile')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='profiler.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('fro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send', to='profiler.profile')),
                ('on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='doctor.notifications')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='profiler.profile')),
            ],
        ),
    ]
