# Generated by Django 3.1.7 on 2021-04-01 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate_disease', models.CharField(blank=True, max_length=100, null=True)),
                ('did_work', models.BooleanField(default=False)),
                ('diagnosis_text', models.TextField(blank=True, null=True)),
                ('type_of_test', models.CharField(choices=[('cs', 'Cassava'), ('bn', 'Bean')], max_length=10)),
                ('feedbacks', models.TextField(blank=True, max_length=1000, null=True)),
                ('tested_on', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
